version: "3.8"

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
  publisher:
    build: publisher
    ports:
      - 3001:3001
    volumes:
      - ./publisher:/app
