services:
  frontend:
    build: ./frontend
    ports:
      - 4007:4007
    volumes:
      - ./frontend:/app
    environment:
      GOOGLE_CLIENT_ID: 585292133303-3ptuj94223ef78ir7u5d3ce9hcn0vfnm.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXT_PUBLIC_MYCHARTS_PRIMARY_COLOR: "#390050"
      NEXT_PUBLIC_URL_FRONTEND_ADAPTER: http://localhost:4008
      NEXTAUTH_SECRET: td7o5GEO+wnpLfHNTiDbt6kJiqxlHfZhEtyDPPSD8JY=
      NEXTAUTH_URL: http://localhost:4007
      PORT: 4007

  # TODO Break adapter into multiple pieces (even by chart type, or by function (e.g. buy credits, get chart etc.))
  service-frontend-adapter:
    build: ./service-frontend-adapter
    volumes:
      - ./service-frontend-adapter:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-frontend-adapter
      KAFKA_GROUP_ID: service-frontend-adapter
      KAFKA_TOPIC_CHART_CREATE_BUBBLE_REQUEST: chart-create-bubble-request
      KAFKA_TOPIC_CHART_CREATE_LINE_REQUEST: chart-create-line-request
      KAFKA_TOPIC_CHART_CREATE_MULTI_AXIS_LINE_REQUEST: chart-create-multi-axis-line-request
      KAFKA_TOPIC_CHART_CREATE_POLAR_AREA_REQUEST: chart-create-polar-area-request
      KAFKA_TOPIC_CHART_CREATE_RADAR_REQUEST: chart-create-radar-request
      KAFKA_TOPIC_CHART_CREATE_SCATTER_REQUEST: chart-create-scatter-request
      KAFKA_TOPIC_CHART_GET_BUBBLE_REQUEST: chart-get-bubble-request
      KAFKA_TOPIC_CHART_GET_LINE_REQUEST: chart-get-line-request
      KAFKA_TOPIC_CHART_GET_MULTI_AXIS_LINE_REQUEST: chart-get-multi-axis-line-request
      KAFKA_TOPIC_CHART_GET_POLAR_AREA_REQUEST: chart-get-polar-area-request
      KAFKA_TOPIC_CHART_GET_RADAR_REQUEST: chart-get-radar-request
      KAFKA_TOPIC_CHART_GET_SCATTER_REQUEST: chart-get-scatter-request
      KAFKA_TOPIC_CREDITS_BUY_REQUEST: credits-buy-request
      KAFKA_TOPIC_LAST_LOGIN_UPDATE_REQUEST: last-login-update-request
      KAFKA_TOPIC_USER_CREATE_REQUEST: user-create-request
      KAFKA_TOPIC_USER_GET_REPLY: user-get-reply
      KAFKA_TOPIC_USER_GET_REQUEST: user-get-request
      PORT: 4008
    ports:
      - 4008:4008

  service-user-data:
    build: ./service-user-data
    volumes:
      - ./service-user-data:/app
    environment:
      # TODO Change authSource=admin, root/example
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-user-data
      KAFKA_GROUP_ID: service-user-data
      KAFKA_TOPIC_CREDITS_BUY_REQUEST: credits-buy-request
      KAFKA_TOPIC_USER_GET_REPLY: user-get-reply
      KAFKA_TOPIC_USER_GET_REQUEST: user-get-request
      KAFKA_TOPIC_USER_CREATE_REQUEST: user-create-request
      KAFKA_TOPIC_LAST_LOGIN_UPDATE_REQUEST: last-login-update-request
      MONGO_URI: mongodb://root:example@service-user-data-mongo:27017/Users?authSource=admin

  service-user-data-mongo:
    image: mongo:6-jammy
    environment:
      # TODO Change these
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  service-chart-create-bubble:
    build: ./service-chart-create-bubble
    volumes:
      - ./service-chart-create-bubble:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-bubble
      KAFKA_GROUP_ID: service-chart-create-bubble
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-bubble-request
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-bubble-request

  service-chart-create-line:
    build: ./service-chart-create-line
    volumes:
      - ./service-chart-create-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-line
      KAFKA_GROUP_ID: service-chart-create-line
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-line-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-line-request

  service-chart-create-multi-axis-line:
    build: ./service-chart-create-multi-axis-line
    volumes:
      - ./service-chart-create-multi-axis-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-multi-axis-line
      KAFKA_GROUP_ID: service-chart-create-multi-axis-line
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-multi-axis-line-request
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-multi-axis-line-request

  service-chart-create-polar-area:
    build: ./service-chart-create-polar-area
    volumes:
      - ./service-chart-create-polar-area:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-polar-area
      KAFKA_GROUP_ID: service-chart-create-polar-area
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-polar-area-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-polar-area-request

  service-chart-create-radar:
    build: ./service-chart-create-radar
    volumes:
      - ./service-chart-create-radar:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-radar
      KAFKA_GROUP_ID: service-chart-create-radar
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-radar-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-radar-request

  service-chart-create-scatter:
    build: ./service-chart-create-scatter
    volumes:
      - ./service-chart-create-scatter:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-scatter
      KAFKA_GROUP_ID: service-chart-create-scatter
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-scatter-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-scatter-request

  service-chart-store-bubble:
    build: ./service-chart-store-bubble
    volumes:
      - ./service-chart-store-bubble:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-bubble-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-bubble-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-bubble-response

  service-chart-store-line:
    build: ./service-chart-store-line
    volumes:
      - ./service-chart-store-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-line-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-line-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-line-response

  service-chart-store-multi-axis-line:
    build: ./service-chart-store-multi-axis-line
    volumes:
      - ./service-chart-store-multi-axis-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-multi-axis-line-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-multi-axis-line-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-multi-axis-line-response

  service-chart-store-polar-area:
    build: ./service-chart-store-polar-area
    volumes:
      - ./service-chart-store-polar-area:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-polar-area-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-polar-area-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-polar-area-response

  service-chart-store-radar:
    build: ./service-chart-store-radar
    volumes:
      - ./service-chart-store-radar:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-radar-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-radar-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-radar-response

  service-chart-store-scatter:
    build: ./service-chart-store-scatter
    volumes:
      - ./service-chart-store-scatter:/app
    environment:
      KAFKA_BROKER: kafka:9092
      MONGO_URI:
      PORT:
      CHART_NAME:
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-scatter-request
      KAFKA_TOPIC_GET_CHART_REQUEST: chart-get-scatter-request
      KAFKA_TOPIC_GET_CHART_RESPONSE: chart-get-scatter-response

  service-chart-template-download:
    build: ./service-chart-template-download
    volumes:
      - ./service-chart-template-download:/app
    environment:
      KAFKA_BROKER: kafka:9092
