services:
  frontend:
    build: ./frontend
    ports:
      - 4007:4007
    volumes:
      - ./frontend:/app
    environment:
      GOOGLE_CLIENT_ID: 585292133303-3ptuj94223ef78ir7u5d3ce9hcn0vfnm.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXT_PUBLIC_MYCHARTS_PRIMARY_COLOR: "#390050"
      NEXT_PUBLIC_URL_CHART_CREATE: http://localhost:4008/createChart
      NEXT_PUBLIC_URL_CHART_DOWNLOAD: http://localhost:4008/downloadChart
      NEXT_PUBLIC_URL_CHARTLIST_GET: http://localhost:4008/getChartList
      NEXT_PUBLIC_URL_CREDITS_UPDATE: http://localhost:4008/updateCredits
      NEXT_PUBLIC_URL_LAST_LOGIN_UPDATE: http://localhost:4008/updateLastLogin
      NEXT_PUBLIC_URL_NUMCHARTS_INCREMENT: http://localhost:4008/numChartsIncrement
      NEXT_PUBLIC_URL_USER_CREATE: http://localhost:4008/createUser
      NEXT_PUBLIC_URL_USER_GET: http://localhost:4008/getUser
      NEXTAUTH_SECRET: td7o5GEO+wnpLfHNTiDbt6kJiqxlHfZhEtyDPPSD8JY=
      NEXTAUTH_URL: http://localhost:4007
      PORT: 4007

  service-chart-create-bubble:
    build: ./service-chart-create-bubble
    volumes:
      - ./service-chart-create-bubble:/app
    environment:
      CHART_HEIGHT: 400
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-bubble
      KAFKA_GROUP_ID: service-chart-create-bubble
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-bubble-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-bubble-request

  service-chart-create-line:
    build: ./service-chart-create-line
    volumes:
      - ./service-chart-create-line:/app
    environment:
      CHART_HEIGHT: 400
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-line
      KAFKA_GROUP_ID: service-chart-create-line
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-line-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-line-request

  service-chart-create-multi-axis-line:
    build: ./service-chart-create-multi-axis-line
    volumes:
      - ./service-chart-create-multi-axis-line:/app
    environment:
      CHART_HEIGHT: 400
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-multi-axis-line
      KAFKA_GROUP_ID: service-chart-create-multi-axis-line
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-multi-axis-line-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-multi-axis-line-request

  service-chart-create-polar-area:
    build: ./service-chart-create-polar-area
    volumes:
      - ./service-chart-create-polar-area:/app
    environment:
      CHART_HEIGHT: 800
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-polar-area
      KAFKA_GROUP_ID: service-chart-create-polar-area
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-polar-area-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-polar-area-request

  service-chart-create-radar:
    build: ./service-chart-create-radar
    volumes:
      - ./service-chart-create-radar:/app
    environment:
      CHART_HEIGHT: 800
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-radar
      KAFKA_GROUP_ID: service-chart-create-radar
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-radar-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-radar-request

  service-chart-create-scatter:
    build: ./service-chart-create-scatter
    volumes:
      - ./service-chart-create-scatter:/app
    environment:
      CHART_HEIGHT: 400
      CHART_WIDTH: 800
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-create-scatter
      KAFKA_GROUP_ID: service-chart-create-scatter
      KAFKA_TOPIC_CHART_CREATE_REQUEST: chart-create-scatter-request
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-scatter-request

  service-chart-store-bubble:
    build: ./service-chart-store-bubble
    volumes:
      - ./service-chart-store-bubble:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-bubble
      KAFKA_GROUP_ID: service-chart-store-bubble
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-bubble-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-bubble-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-bubble-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-bubble-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-bubble-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-bubble-mongo:27017/Charts?authSource=admin

  service-chart-store-bubble-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  service-chart-store-line:
    build: ./service-chart-store-line
    volumes:
      - ./service-chart-store-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-line
      KAFKA_GROUP_ID: service-chart-store-line
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-line-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-line-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-line-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-line-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-line-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-line-mongo:27017/Charts?authSource=admin

  service-chart-store-line-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  service-chart-store-multi-axis-line:
    build: ./service-chart-store-multi-axis-line
    volumes:
      - ./service-chart-store-multi-axis-line:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-multi-axis-line
      KAFKA_GROUP_ID: service-chart-store-multi-axis-line
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-multi-axis-line-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-multi-axis-line-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-multi-axis-line-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-multi-axis-line-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-multi-axis-line-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-multi-axis-line-mongo:27017/Charts?authSource=admin

  service-chart-store-multi-axis-line-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  service-chart-store-polar-area:
    build: ./service-chart-store-polar-area
    volumes:
      - ./service-chart-store-polar-area:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-polar-area
      KAFKA_GROUP_ID: service-chart-store-polar-area
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-polar-area-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-polar-area-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-polar-area-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-polar-area-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-polar-area-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-polar-area-mongo:27017/Charts?authSource=admin

  service-chart-store-polar-area-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  service-chart-store-radar:
    build: ./service-chart-store-radar
    volumes:
      - ./service-chart-store-radar:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-radar
      KAFKA_GROUP_ID: service-chart-store-radar
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-radar-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-radar-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-radar-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-radar-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-radar-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-radar-mongo:27017/Charts?authSource=admin

  service-chart-store-radar-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  service-chart-store-scatter:
    build: ./service-chart-store-scatter
    volumes:
      - ./service-chart-store-scatter:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-chart-store-scatter
      KAFKA_GROUP_ID: service-chart-store-scatter
      KAFKA_TOPIC_CHART_DOWNLOAD_REQUEST: chart-download-scatter-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RESPONSE: chart-download-scatter-response
      KAFKA_TOPIC_CHART_SAVE_REQUEST: chart-save-scatter-request
      KAFKA_TOPIC_CHARTLIST_GET_REQUEST: chartlist-get-scatter-request
      KAFKA_TOPIC_CHARTLIST_GET_RESPONSE: chartlist-get-scatter-response
      MONGO_URI: mongodb://myUsername:myPassword@service-chart-store-scatter-mongo:27017/Charts?authSource=admin

  service-chart-store-scatter-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  # TODO Break adapter into multiple pieces (even by chart type, or by function (e.g. buy credits, get chart etc.))
  service-frontend-adapter:
    build: ./service-frontend-adapter
    volumes:
      - ./service-frontend-adapter:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-frontend-adapter
      KAFKA_GROUP_ID: service-frontend-adapter
      KAFKA_TOPIC_CHART_CREATE_BUBBLE_REQUEST: chart-create-bubble-request
      KAFKA_TOPIC_CHART_CREATE_LINE_REQUEST: chart-create-line-request
      KAFKA_TOPIC_CHART_CREATE_MULTI_AXIS_LINE_REQUEST: chart-create-multi-axis-line-request
      KAFKA_TOPIC_CHART_CREATE_POLAR_AREA_REQUEST: chart-create-polar-area-request
      KAFKA_TOPIC_CHART_CREATE_RADAR_REQUEST: chart-create-radar-request
      KAFKA_TOPIC_CHART_CREATE_SCATTER_REQUEST: chart-create-scatter-request
      KAFKA_TOPIC_CHART_DOWNLOAD_BUBBLE_REQUEST: chart-download-bubble-request
      KAFKA_TOPIC_CHART_DOWNLOAD_BUBBLE_RESPONSE: chart-download-bubble-response
      KAFKA_TOPIC_CHART_DOWNLOAD_LINE_REQUEST: chart-download-line-request
      KAFKA_TOPIC_CHART_DOWNLOAD_LINE_RESPONSE: chart-download-line-response
      KAFKA_TOPIC_CHART_DOWNLOAD_MULTI_AXIS_LINE_REQUEST: chart-download-multi-axis-line-request
      KAFKA_TOPIC_CHART_DOWNLOAD_MULTI_AXIS_LINE_RESPONSE: chart-download-multi-axis-line-response
      KAFKA_TOPIC_CHART_DOWNLOAD_POLAR_AREA_REQUEST: chart-download-polar-area-request
      KAFKA_TOPIC_CHART_DOWNLOAD_POLAR_AREA_RESPONSE: chart-download-polar-area-response
      KAFKA_TOPIC_CHART_DOWNLOAD_RADAR_REQUEST: chart-download-radar-request
      KAFKA_TOPIC_CHART_DOWNLOAD_RADAR_RESPONSE: chart-download-radar-response
      KAFKA_TOPIC_CHART_DOWNLOAD_SCATTER_REQUEST: chart-download-scatter-request
      KAFKA_TOPIC_CHART_DOWNLOAD_SCATTER_RESPONSE: chart-download-scatter-response
      KAFKA_TOPIC_CHARTLIST_GET_BUBBLE_REQUEST: chartlist-get-bubble-request
      KAFKA_TOPIC_CHARTLIST_GET_BUBBLE_RESPONSE: chartlist-get-bubble-response
      KAFKA_TOPIC_CHARTLIST_GET_LINE_REQUEST: chartlist-get-line-request
      KAFKA_TOPIC_CHARTLIST_GET_LINE_RESPONSE: chartlist-get-line-response
      KAFKA_TOPIC_CHARTLIST_GET_MULTI_AXIS_LINE_REQUEST: chartlist-get-multi-axis-line-request
      KAFKA_TOPIC_CHARTLIST_GET_MULTI_AXIS_LINE_RESPONSE: chartlist-get-multi-axis-line-response
      KAFKA_TOPIC_CHARTLIST_GET_POLAR_AREA_REQUEST: chartlist-get-polar-area-request
      KAFKA_TOPIC_CHARTLIST_GET_POLAR_AREA_RESPONSE: chartlist-get-polar-area-response
      KAFKA_TOPIC_CHARTLIST_GET_RADAR_REQUEST: chartlist-get-radar-request
      KAFKA_TOPIC_CHARTLIST_GET_RADAR_RESPONSE: chartlist-get-radar-response
      KAFKA_TOPIC_CHARTLIST_GET_SCATTER_REQUEST: chartlist-get-scatter-request
      KAFKA_TOPIC_CHARTLIST_GET_SCATTER_RESPONSE: chartlist-get-scatter-response
      KAFKA_TOPIC_CREDITS_UPDATE_REQUEST: credits-update-request
      KAFKA_TOPIC_LAST_LOGIN_UPDATE_REQUEST: last-login-update-request
      KAFKA_TOPIC_NUMCHARTS_INCREMENT_REQUEST: numCharts-increment-request
      KAFKA_TOPIC_USER_CREATE_REQUEST: user-create-request
      KAFKA_TOPIC_USER_GET_REQUEST: user-get-request
      KAFKA_TOPIC_USER_GET_RESPONSE: user-get-response
      PORT: 4008
      URL_CHART_CREATE: createChart
      URL_CHART_DOWNLOAD: downloadChart
      URL_CHARTLIST_GET: getChartList
      URL_CREDITS_UPDATE: updateCredits
      URL_LAST_LOGIN_UPDATE: updateLastLogin
      URL_NUMCHARTS_INCREMENT: numChartsIncrement
      URL_USER_CREATE: createUser
      URL_USER_GET: getUser

    ports:
      - 4008:4008

  service-user-data:
    build: ./service-user-data
    volumes:
      - ./service-user-data:/app
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: service-user-data
      KAFKA_GROUP_ID: service-user-data
      KAFKA_TOPIC_CREDITS_UPDATE_REQUEST: credits-update-request
      KAFKA_TOPIC_LAST_LOGIN_UPDATE_REQUEST: last-login-update-request
      KAFKA_TOPIC_NUMCHARTS_INCREMENT_REQUEST: numCharts-increment-request
      KAFKA_TOPIC_USER_CREATE_REQUEST: user-create-request
      KAFKA_TOPIC_USER_GET_REQUEST: user-get-request
      KAFKA_TOPIC_USER_GET_RESPONSE: user-get-response
      MONGO_URI: mongodb://myUsername:myPassword@service-user-data-mongo:27017/Users?authSource=admin

  service-user-data-mongo:
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_ROOT_PASSWORD: myPassword
      MONGO_INITDB_ROOT_USERNAME: myUsername

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
