# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build: app
    ports:
      - 3001:3001
  mongo:
    build: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  insert-data:
    build: insert-data
